openapi: 3.1.0
info:
  title: Salud La Ceiba API
  version: "1.0.0"
servers:
  - url: http://localhost:4000/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # ---------- Autenticación ----------
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:    { type: string, format: email }
        password: { type: string }
    TokenResponse:
      type: object
      properties:
        accessToken:  { type: string }
        refreshToken: { type: string }
    RefreshRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken: { type: string }
    LogoutRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken: { type: string }

    # ---------- Usuarios & Roles ----------
    UserList:
      type: object
      properties:
        meta:
          type: object
          properties:
            page:  { type: integer }
            limit: { type: integer }
            total: { type: integer }
        data:
          type: array
          items: { $ref: '#/components/schemas/User' }
    User:
      type: object
      properties:
        user_id:   { type: integer }
        nombre:    { type: string }
        email:     { type: string }
        rol:       { type: string }
        activo:    { type: integer }
        creado_en: { type: string, format: date-time }
        persona_id:{ type: integer, nullable: true }

    CreateUserRequest:
      type: object
      required: [nombre,email,rol,password]
      properties:
        nombre:     { type: string }
        email:      { type: string, format: email }
        rol:        { type: string }
        password:   { type: string, format: password }
        persona_id: { type: integer }

    UpdateUserRequest:
      type: object
      properties:
        nombre:   { type: string }
        email:    { type: string, format: email }
        rol:      { type: string }
        password: { type: string, format: password }
        activo:   { type: boolean }
      minProperties: 1

    Role:
      type: object
      properties:
        role_id: { type: integer }
        name:    { type: string }

    # ---------- Territorios & Sectores ----------
    Territorio:
      type: object
      properties:
        territorio_id: { type: integer }
        codigo:        { type: string }
        nombre:        { type: string }

    SectorGeoJSON:
      type: object
      description: GeoJSON FeatureCollection

    CreateSector:
      type: object
      required: [territorio_id,nombre,geom]
      properties:
        territorio_id: { type: integer }
        nombre:        { type: string }
        geom:          { type: object }

    Error:
      type: object
      properties:
        error:   { type: string }
        message: { type: string }

security:
  - bearerAuth: []

paths:
  # ========================================
  # 🔐 AUTENTICACIÓN
  # ========================================
  /auth/login:
    post:
      tags: [Autenticación]
      summary: Inicio de sesión
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/LoginRequest' }
      responses:
        "200": { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/TokenResponse' } } } }
        "401": { description: Credenciales inválidas, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }

  /auth/refresh:
    post:
      tags: [Autenticación]
      summary: Renueva access-token
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/RefreshRequest' }
      responses:
        "200": { description: OK, content: { application/json: { schema: { type: object, properties: { accessToken: { type: string } } } } } }
        "401": { description: Refresh inválido, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }

  /auth/logout:
    post:
      tags: [Autenticación]
      summary: Cierra sesión
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/LogoutRequest' }
      responses:
        "200": { description: Sesión terminada, content: { application/json: { schema: { type: object, properties: { message: { type: string } } } } } }

  # ========================================
  # 👥 USUARIOS Y ROLES
  # ========================================
  /users:
    get:
      tags: [Usuarios]
      summary: Lista paginada de usuarios
      parameters:
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 20 }
        - in: query
          name: rol
          schema: { type: string }
        - in: query
          name: activo
          schema: { type: boolean }
        - in: query
          name: q
          schema: { type: string }
      responses:
        "200": { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/UserList' } } } }
    post:
      tags: [Usuarios]
      summary: Crea un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CreateUserRequest' }
      responses:
        "201": { description: Creado, content: { application/json: { schema: { $ref: '#/components/schemas/User' } } } }

  /users/{id}:
    get:
      tags: [Usuarios]
      summary: Obtiene un usuario
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        "200": { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/User' } } } }
        "404": { description: No encontrado, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }

    put:
      tags: [Usuarios]
      summary: Actualiza un usuario
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/UpdateUserRequest' }
      responses:
        "200": { description: OK, content: { application/json: { schema: { type: object, properties: { message: { type: string } } } } } }

    delete:
      tags: [Usuarios]
      summary: Desactiva un usuario
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        "204": { description: Sin contenido }

  /roles:
    get:
      tags: [Usuarios]
      summary: Devuelve catálogo de roles
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Role' }

  # ========================================
  # 🗺️ SECTORIZACIÓN
  # ========================================
  /territorios:
    get:
      tags: [Sectorización]
      summary: Lista de territorios
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Territorio' }

  /territorios/{id}/sectores:
    get:
      tags: [Sectorización]
      summary: Sectores por territorio
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
        - in: query
          name: includeStats
          schema: { type: boolean }
      responses:
        "200": { description: OK }
        "404": { description: No encontrado, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }

  /sectores:
    get:
      tags: [Sectorización]
      summary: GeoJSON de sectores
      parameters:
        - in: query
          name: bbox
          schema: { type: string, example: "-91.4,14.7,-91.2,14.9" }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/SectorGeoJSON' }
    post:
      tags: [Sectorización]
      summary: Crear sector
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CreateSector' }
      responses:
        "201": { description: Creado }
        "400": { description: Error de validación, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }

  /sectores/{id}:
    get:
      tags: [Sectorización]
      summary: Ficha sector
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200": { description: OK }
        "404": { description: No encontrado, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
    put:
      tags: [Sectorización]
      summary: Editar sector
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CreateSector' }
      responses:
        "200": { description: OK }
        "400": { description: Error de validación, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
    delete:
      tags: [Sectorización]
      summary: Desactivar sector
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "204": { description: Sin contenido }
        "400": { description: Sector con viviendas activas, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }

  /sectores/{id}/viviendas:
    get:
      tags: [Sectorización]
      summary: Viviendas por sector
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 20 }
        - in: query
          name: withGPS
          schema: { type: boolean }
      responses:
        "200": { description: OK } 